name: CI workflow

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 22.0.0

jobs:
  unit_test:
    runs-on: ubuntu-latest
    name: Checkout and Setup Node
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm run test
  notifier:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - name: Echo Workflows
        run: echo "Node version ${{env.NODE_VERSION}}!"
